/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WrappedError, WrappedErrorTrace, WrappedErrorTraceList } from "./utils/utils";
export { WrappedError, WrappedErrorTrace, WrappedErrorTraceList } from "./utils/utils";
export namespace Components {
    interface ApieClassDisplay {
        "phpClassName": string;
    }
    interface ApieExceptionDisplay {
        "code"?: number;
        "message"?: string;
        "phpClassName"?: string;
        "phpVersion"?: string;
        "trace"?: WrappedErrorTraceList;
    }
    interface ApieFilterOverview {
        "filterNames": string[];
        "inputPrefix": string;
    }
    interface ApieRenderCode {
        "code": string;
        "highlightLine": number;
        "linesToDisplay": number;
    }
    interface ApieStackDisplay {
        "trace": Array<WrappedErrorTrace>;
    }
    interface ApieStacktrace {
        "exceptions": Array<WrappedError>;
        "phpVersion": string;
    }
}
declare global {
    interface HTMLApieClassDisplayElement extends Components.ApieClassDisplay, HTMLStencilElement {
    }
    var HTMLApieClassDisplayElement: {
        prototype: HTMLApieClassDisplayElement;
        new (): HTMLApieClassDisplayElement;
    };
    interface HTMLApieExceptionDisplayElement extends Components.ApieExceptionDisplay, HTMLStencilElement {
    }
    var HTMLApieExceptionDisplayElement: {
        prototype: HTMLApieExceptionDisplayElement;
        new (): HTMLApieExceptionDisplayElement;
    };
    interface HTMLApieFilterOverviewElement extends Components.ApieFilterOverview, HTMLStencilElement {
    }
    var HTMLApieFilterOverviewElement: {
        prototype: HTMLApieFilterOverviewElement;
        new (): HTMLApieFilterOverviewElement;
    };
    interface HTMLApieRenderCodeElement extends Components.ApieRenderCode, HTMLStencilElement {
    }
    var HTMLApieRenderCodeElement: {
        prototype: HTMLApieRenderCodeElement;
        new (): HTMLApieRenderCodeElement;
    };
    interface HTMLApieStackDisplayElement extends Components.ApieStackDisplay, HTMLStencilElement {
    }
    var HTMLApieStackDisplayElement: {
        prototype: HTMLApieStackDisplayElement;
        new (): HTMLApieStackDisplayElement;
    };
    interface HTMLApieStacktraceElement extends Components.ApieStacktrace, HTMLStencilElement {
    }
    var HTMLApieStacktraceElement: {
        prototype: HTMLApieStacktraceElement;
        new (): HTMLApieStacktraceElement;
    };
    interface HTMLElementTagNameMap {
        "apie-class-display": HTMLApieClassDisplayElement;
        "apie-exception-display": HTMLApieExceptionDisplayElement;
        "apie-filter-overview": HTMLApieFilterOverviewElement;
        "apie-render-code": HTMLApieRenderCodeElement;
        "apie-stack-display": HTMLApieStackDisplayElement;
        "apie-stacktrace": HTMLApieStacktraceElement;
    }
}
declare namespace LocalJSX {
    interface ApieClassDisplay {
        "phpClassName"?: string;
    }
    interface ApieExceptionDisplay {
        "code"?: number;
        "message"?: string;
        "phpClassName"?: string;
        "phpVersion"?: string;
        "trace"?: WrappedErrorTraceList;
    }
    interface ApieFilterOverview {
        "filterNames"?: string[];
        "inputPrefix"?: string;
    }
    interface ApieRenderCode {
        "code"?: string;
        "highlightLine"?: number;
        "linesToDisplay"?: number;
    }
    interface ApieStackDisplay {
        "trace"?: Array<WrappedErrorTrace>;
    }
    interface ApieStacktrace {
        "exceptions"?: Array<WrappedError>;
        "phpVersion"?: string;
    }
    interface IntrinsicElements {
        "apie-class-display": ApieClassDisplay;
        "apie-exception-display": ApieExceptionDisplay;
        "apie-filter-overview": ApieFilterOverview;
        "apie-render-code": ApieRenderCode;
        "apie-stack-display": ApieStackDisplay;
        "apie-stacktrace": ApieStacktrace;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "apie-class-display": LocalJSX.ApieClassDisplay & JSXBase.HTMLAttributes<HTMLApieClassDisplayElement>;
            "apie-exception-display": LocalJSX.ApieExceptionDisplay & JSXBase.HTMLAttributes<HTMLApieExceptionDisplayElement>;
            "apie-filter-overview": LocalJSX.ApieFilterOverview & JSXBase.HTMLAttributes<HTMLApieFilterOverviewElement>;
            "apie-render-code": LocalJSX.ApieRenderCode & JSXBase.HTMLAttributes<HTMLApieRenderCodeElement>;
            "apie-stack-display": LocalJSX.ApieStackDisplay & JSXBase.HTMLAttributes<HTMLApieStackDisplayElement>;
            "apie-stacktrace": LocalJSX.ApieStacktrace & JSXBase.HTMLAttributes<HTMLApieStacktraceElement>;
        }
    }
}
